config/routes.rb
JavaSubmissionTester::Engine.routes.draw do
  get 'pages/:page', to: 'pages#show', as: 'pages'
end

app/controllers/java_submission_tester/pages_controller.rb
module JavaSubmissionTester
  class PagesController < ::ApplicationController
    layout "application"

    def show
      puts params[:page]
      render action: params[:page]
    end
  end
end

app/views/java_submission_tester/pages/how_to_jar.html.slim
= stylesheet_link_tag 'java_submission_tester/help'
= javascript_include_tag 'java_submission_tester/image-zoom'

= content_for :title
  | Hilfe - Wie erstelle ich eine Jar-Datei - IntelliJ

h1.text-center
  | Wie erstelle ich eine Jar-Datei in IntelliJ?
ol
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/start.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        | Öffne das IntelliJ Projekt, für das eine Jar-Datei erstellt werden soll.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/file-menu.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Öffne das Menü
        em File > Project Structure
        | .

  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/project-structure-artifacts.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Navigiere zu dem Menü
        em> Artifacts
        | auf der linken Seite.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/project-structure-artifacts-add.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Öffne über das grüne + das Auswahl Menü für die Artifacts.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/artifacts-jar.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Wähle die Option
        em Jar > from module with dependencies
        |.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-artifact-dialog.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        | Bestätige das Erstellen des Artefaktes mit Standardeinstellungen.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-jar-content.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        | Öffne über das grüne + das Menü um zusätzliche Inhalte in die Jar-Datei zu packen.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-jar-content-dir.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Wähle die Option
        em Directory Content
        |.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-jar-content-dir-src.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Wähle in dem Pop-up, das sich geöffnet hat den Ordner aus, der die Java-Dateien enthält. Dies ist standardmäßig
          der Ordner
        em src
        ' . Wähle
        strong> NICHT
        ' den Ordner, der das Projekt enthält, sonst werden viele unnötige Dateien in die Jar-Datei gepackt. Danach
          bestätige die Auswahl und schließe das Pop-up.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/menu-build-artifacts.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Um die Jar-Datei zu bauen, navigiere zu
        em Build > Build Artifacts...
        | .
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/artifact-build.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' In dem Pop-up das sich geöffnet hat die Aktion
        em> Build
        ' auswählen.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/finish.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Herzlichen Glückwunsch. Die fertige Jar-Datei wird in dem Ordner
        em> out/artifacts/...
        ' abgelegt.

app/views/java_submission_tester/pages/student_help_io.html.slim
h1
  | Hilfe

h3
  | Allgemein

p
  ' IO-Aufgaben generieren für jede Person eine individuelle Eingabe, mit der eine Aufgabe gelöst werden soll.
  ' Das Ergebnis einer Aufgabe ist wieder ein Text, der von Dozentron automatisch bewertet wird.
  ' Zusätzlich zu dem Ergebnistext kann auch der Quellcode des Programms abgegeben werden, dass die Aufgabe gelöst hat.
  ' Dieses Programm wird von Dozentron
  strong> NICHT
  ' ausgeführt. Die Abgabe des Quellcodes ist nur für den Dozenten und die Tutoren, damit Sie sich ihre Ergebnisse noch
  ' einmal ansehen und von Hand bewerten können.

app/views/java_submission_tester/pages/student_help_submission.html.slim
= stylesheet_link_tag 'java_submission_tester/help'

= content_for :title
  | Java Tester Hilfe

.row
  h1
    | Hilfe

.row
  h2
    | Wie erstelle ich eine Jar?
  .col-sm-12
    = link_to pages_path(:how_to_jar), class: 'large'
      => image_tag 'java_submission_tester/IntelliJ_IDEA_Logo.svg'
      | IntelliJ

app/views/java_submission_tester/pages/teacher_help_io.html.slim
h1
  | Here I am walking
' like a !!!

app/views/java_submission_tester/pages/teacher_help_io_junit.html.slim
h1
  | Beispiel für einen Test für IO-Task mit Junit4

pre
  |
    package de.thm.mni;

    import org.junit.Assert;
    import org.junit.Before;
    import org.junit.Test;

    import java.io.IOException;
    import java.nio.file.Files;
    import java.nio.file.Paths;

    public class InputOutputTest {
        private String systemInput;
        private String studentOutput;

        @Before
        public void loadFiles() {
            systemInput = System.getProperty("input");
            studentOutput = System.getProperty("student-output");
        }

        @Test
        public void correctNumber() throws IOException {
            String input = new String(Files.readAllBytes(Paths.get(systemInput)));
            int expectedOutput = input.trim().length();
            int gotOutput;

            gotOutput = Integer.parseInt(new String(Files.readAllBytes(Paths.get(studentOutput))).trim());

            if(expectedOutput > gotOutput)
                Assert.fail("Die gesuchte Zahl ist größer!");
            else if(expectedOutput < gotOutput)
                Assert.fail("Die gesuchte Zahl ist kleiner!");

        }

        @Test
        public void assertFilesSet() {
            Assert.assertNotNull(systemInput);
            Assert.assertNotNull(studentOutput);
        }
    }

app/views/java_submission_tester/pages/teacher_help_submission.html.slim
h1
  | Here I am walking
' like a hurric ane!!!